name: Korabli_chs_Setup

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Find Visual Studio Path
      shell: powershell
      run: |
        $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -version 17.0 -products * -property installationPath
        echo "VS_PATH=$vsPath" >> $env:GITHUB_ENV

    - name: Install VS Installer Projects
      run: |
        $vsixUrl = "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/VisualStudioClient/vsextensions/MicrosoftVisualStudio2017InstallerProjects/1.0.0/vspackage"
        $vsixPath = "$env:RUNNER_TEMP\InstallerProjects.vsix"
        Invoke-WebRequest -Uri $vsixUrl -OutFile $vsixPath
        Start-Process -Wait -FilePath "${env:VS_PATH}\Common7\IDE\VSIXInstaller.exe" -ArgumentList "/q /a $vsixPath"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3
      with:
        vs-version: '17.0'  # VS 2022

    - name: Build solution
      run: |
        # 提取版本号（从release名称或标签）
        $version = "${{ github.event.release.tag_name }}"
        Write-Host "Building version: $version"
        
        $msbuildPath = & "${env:VS_PATH}\MSBuild\Current\Bin\MSBuild.exe"
        msbuild Korabli_chs_Setup.sln /p:Configuration=Release /p:DeployOnBuild=true

    - name: Upload assets to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Korabli_chs_Setup/Release/*.exe
          Korabli_chs_Setup/Release/*.msi
        tag_name: ${{ github.event.release.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}